[babel]

[babel.root]
path = "/Users/john.doe/.babel/db"
description_file = "babel"

[babel.root.inbox]
name = "0-inbox"
description = """
This is for storing immediate tasks, reminders, and plans. Often refer to recent or temporary information.
Here is the first place for unprocessed information, ideas, or tasks that you want to remember or deal with later to refine and organize them into the right category.

- Quick notes.
- Day plan and agenda.
- To-Do lists.
- Agenda and plan for the day.
- Quick ideas.
- Quick plans, etc.
"""

[babel.root.areas]
name = "areas"
description = "Long-term responsibilities I want to manage over time"

[babel.root.projects]
name = "projects"
description = "Short-term efforts (in my work or personal life) that I take on with a certain goal in mind"

[babel.root.resources]
name = "resources"
description = """
Interests and vault of resources that may be useful for supporting the other categories. 
Example:
- Cheat sheets with tools and commands.
- Whishlist (Books, movies, places).
- Notes from books, articles, etc.
"""

[babel.root.archive]
name = "z-archive"
description = "Inactive items from the other 3 categories"